---
- name: install apche2  
  hosts: all
  become: yes
  tasks:
   - name:  instal apache2 If DEBIAN
     apt: name=apache2 state=present update_cache=yes
     when: ansible_os_family == "Debian"

   - name: instal apache2 If REDHAT
     yum: name=httpd state=present update_cache=yes
     when: ansible_os_family == "RedHat"
     
   - name:  Start DEBIAN
     service:
        name: apache2
        state: started
        enabled: yes
     when:  ansible_os_family == "Debian"
     notify:
      - Restart on Debian
   
   - name: Start REDHAT
     service:
        name: httpd
        state: started
        enabled: yes
     when:  ansible_os_family == "RedHat"
     notify:
      - Restart on RedHat

   - name:  change defalt html with yours
     copy:
         src: index.html
         dest: /var/www/html/

  handlers:
   - name: Restart on Debian
     service: 
        name: apache2
        enabled: yes
     when: ansible_os_family == "Debian"
      
   - name: Restart on RedHat
     service: 
        name: httpd
        enabled: yes
     when: ansible_os_family == "RedHat"